using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AccC3DMetadata.UI;
using Autodesk.Authentication;
using Autodesk.Authentication.Model;
using Autodesk.SDKManager;

namespace AccC3DMetadata
{
    /// <summary>
    /// Wraps the Autodesk Authentication SDK to provide 3-legged OAuth PKCE token acquisition
    /// and silent token refresh for the plugin.
    /// </summary>
    public class AuthService
    {
        private readonly AuthenticationClient _authClient;

        /// <summary>
        /// OAuth 2.0 scopes requested for all tokens.  Must cover both Data Management (hub/project
        /// navigation) and the BIM 360 Document Management API (custom attribute read/write).
        /// </summary>
        private static readonly List<Scopes> _scopes = new()
        {
            Scopes.DataRead, // Read hubs, projects, folders, and items via the Data Management API.
            Scopes.DataWrite, // Required for future write operations against Data Management endpoints.
            Scopes.AccountRead, // Read account and hub metadata.
            Scopes.BucketRead, // Read OSS bucket contents (used for config file download via the OSS API).
            Scopes.BucketCreate,
            Scopes.ViewablesRead,
        };

        /// <summary>
        /// Initialises the service by building the Autodesk SDK manager and creating the
        /// <see cref="AuthenticationClient"/>.
        /// </summary>
        public AuthService()
        {
            var sdkManager = SdkManagerBuilder.Create().Build();
            _authClient = new AuthenticationClient(sdkManager);
        }

        /// <summary>
        /// Silently exchanges a refresh token for a new access token without opening the browser.
        /// </summary>
        /// <param name="clientId">The application's OAuth client ID.</param>
        /// <param name="refreshToken">The refresh token from the previous token response.</param>
        /// <returns>A new <see cref="ThreeLeggedToken"/> containing fresh access and refresh tokens.</returns>
        public async Task<ThreeLeggedToken> RefreshAsync(string clientId, string refreshToken)
            // clientSecret is null for public (PKCE) clients — the SDK accepts null here.
            =>
            await _authClient
                .RefreshTokenAsync(clientId, null, refreshToken, _scopes)
                .ConfigureAwait(false);

        /// <summary>
        /// Performs a complete 3-legged OAuth PKCE authorisation flow:
        /// opens the system browser, listens on the loopback redirect URI for the auth code,
        /// then exchanges the code for tokens using the SDK.
        /// </summary>
        /// <param name="clientId">The application's OAuth client ID.</param>
        /// <param name="codeChallenge">
        /// The SHA-256 base64url hash of the PKCE code verifier, generated by the caller.
        /// </param>
        /// <param name="codeVerifier">
        /// The original random PKCE code verifier string — kept secret by the caller and sent
        /// only during the token exchange, not through the browser.
        /// </param>
        /// <param name="redirectUri">
        /// The loopback HTTP URI that the auth server will redirect to after authorisation
        /// (e.g. <c>http://localhost:8080/</c>).
        /// </param>
        /// <param name="cancellationToken">
        /// Cancels a pending sign-in (e.g. from a "Cancel" action in the caller's UI) by closing
        /// the embedded sign-in window immediately, rather than waiting for it to time out.
        /// </param>
        /// <returns>A <see cref="ThreeLeggedToken"/> containing the access and refresh tokens.</returns>
        /// <exception cref="ArgumentNullException">
        /// <paramref name="clientId"/> or <paramref name="redirectUri"/> is null or whitespace.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// The user closed the sign-in window before completing authorisation.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// The browser could not be launched, or the authorisation server returned an error.
        /// </exception>
        /// <exception cref="TimeoutException">
        /// The user did not complete authorisation within 2 minutes (fallback flow only).
        /// </exception>
        public async Task<ThreeLeggedToken> GetThreeLeggedTokenAsync(
            string clientId,
            string codeChallenge,
            string codeVerifier,
            string redirectUri,
            CancellationToken cancellationToken = default
        )
        {
            if (string.IsNullOrWhiteSpace(clientId))
                throw new ArgumentNullException(nameof(clientId));
            if (string.IsNullOrWhiteSpace(redirectUri))
                throw new ArgumentNullException(nameof(redirectUri));

            // A random per-flow value, echoed back by the auth server and verified against the
            // callback response. Without this, a malicious local process could race the real
            // browser redirect and inject its own authorization code into our loopback listener
            // (login CSRF / auth-code injection) — the state check rejects any mismatched callback.
            string expectedState = Convert.ToBase64String(RandomNumberGenerator.GetBytes(16));

            // Build the authorization URL using the SDK — this includes the PKCE challenge
            // and all required query parameters.
            string authorizeUrl = _authClient.Authorize(
                clientId,
                ResponseType.Code,
                redirectUri,
                _scopes,
                state: expectedState,
                codeChallengeMethod: "S256",
                codeChallenge: codeChallenge
            );

            string authorizationCode;
            try
            {
                // Preferred: an in-process WebView2 window. The user closing it is an immediate,
                // explicit cancellation — there's no lingering listener/port and no multi-minute
                // hang if they abandon the sign-in.
                authorizationCode = await GetAuthorizationCodeViaEmbeddedBrowserAsync(
                        authorizeUrl,
                        redirectUri,
                        expectedState,
                        cancellationToken
                    )
                    .ConfigureAwait(false);
            }
            catch (WebView2RuntimeNotFoundException)
            {
                // Fallback for machines without the WebView2 Runtime installed.
                authorizationCode = await GetAuthorizationCodeViaSystemBrowserAsync(
                        authorizeUrl,
                        redirectUri,
                        expectedState
                    )
                    .ConfigureAwait(false);
            }

            // Exchange the authorisation code for access + refresh tokens.
            // The code verifier is sent here (not during the browser step) — the server hashes it
            // and compares with the challenge to prove the caller holds the original secret.
            return await _authClient
                .GetThreeLeggedTokenAsync(
                    clientId,
                    authorizationCode,
                    redirectUri,
                    codeVerifier: codeVerifier
                )
                .ConfigureAwait(false);
        }

        /// <summary>
        /// Runs the sign-in flow in an in-process <see cref="AuthBrowserWindow"/> and returns the
        /// authorisation code from the intercepted redirect. Validates <paramref name="expectedState"/>
        /// to guard against auth-code injection.
        /// </summary>
        private static async Task<string> GetAuthorizationCodeViaEmbeddedBrowserAsync(
            string authorizeUrl,
            string redirectUri,
            string expectedState,
            CancellationToken cancellationToken
        )
        {
            var window = new AuthBrowserWindow(authorizeUrl, redirectUri);
            Uri redirect = await window
                .WaitForRedirectAsync(cancellationToken)
                .ConfigureAwait(false);

            var query = ParseQueryString(redirect.Query);

            string error = query.TryGetValue("error", out var errVal) ? errVal : null;
            if (!string.IsNullOrEmpty(error))
                throw new InvalidOperationException(
                    $"Authorisation error returned by the server: {error}"
                );

            string returnedState = query.TryGetValue("state", out var stateVal) ? stateVal : null;
            if (returnedState != expectedState)
                throw new InvalidOperationException(
                    "The authorisation callback's state did not match the expected value — "
                        + "rejecting for safety. Please retry the sign-in."
                );

            string code = query.TryGetValue("code", out var codeVal) ? codeVal : null;
            if (string.IsNullOrEmpty(code))
                throw new InvalidOperationException(
                    "The authorisation response did not contain a code."
                );

            return code;
        }

        /// <summary>Parses a URL query string (e.g. <c>?a=1&amp;b=2</c>) without a System.Web dependency.</summary>
        private static Dictionary<string, string> ParseQueryString(string query)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (
                string pair in query
                    .TrimStart('?')
                    .Split('&', StringSplitOptions.RemoveEmptyEntries)
            )
            {
                int eq = pair.IndexOf('=');
                string key = eq < 0 ? pair : pair[..eq];
                string value = eq < 0 ? string.Empty : pair[(eq + 1)..];
                result[WebUtility.UrlDecode(key)] = WebUtility.UrlDecode(value);
            }
            return result;
        }

        /// <summary>
        /// Legacy fallback: opens the system default browser and listens on a loopback
        /// <see cref="HttpListener"/> for the redirect, used only when the WebView2 Runtime is
        /// unavailable. Subject to a 2-minute timeout and local port/URL-ACL requirements.
        /// </summary>
        private static async Task<string> GetAuthorizationCodeViaSystemBrowserAsync(
            string authorizeUrl,
            string redirectUri,
            string expectedState
        )
        {
            string authorizationCode;

            // Start the loopback listener BEFORE opening the browser to avoid a race condition
            // where the browser redirects before the listener is ready.
            using (var listener = new HttpListener())
            {
                // HttpListener requires a trailing slash on the prefix.
                var prefix = redirectUri.TrimEnd('/') + "/";
                listener.Prefixes.Add(prefix);

                try
                {
                    listener.Start();
                }
                catch (HttpListenerException ex)
                {
                    // Common on machines where the redirect URI has never been granted a URL ACL
                    // reservation (error 5, "Access is denied") or where another process already
                    // owns the port (error 32/183). Both fail silently for the caller unless we
                    // translate them into an actionable message here.
                    string hint =
                        ex.NativeErrorCode == 5
                            ? "Access is denied binding to the redirect URI. Run this once from an "
                                + $"elevated command prompt, then retry:\n  netsh http add urlacl url={prefix} user=Everyone"
                            : $"Port {new Uri(prefix).Port} may already be in use by another application "
                                + "(e.g. another AutoCAD session, IIS Express, or a dev server). Close it and retry.";
                    throw new InvalidOperationException(
                        $"Could not start the local sign-in listener on {prefix}: {ex.Message}\n{hint}",
                        ex
                    );
                }

                try
                {
                    Process.Start(
                        new ProcessStartInfo
                        {
                            FileName = authorizeUrl,
                            UseShellExecute = true, // Required for the OS default browser to handle the URL.
                        }
                    );
                }
                catch
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        $"Unable to open the system browser. Open this URL manually:\n{authorizeUrl}"
                    );
                }

                // Wait for the browser redirect, with a 2-minute timeout to avoid hanging forever.
                var contextTask = listener.GetContextAsync();
                var completed = await Task.WhenAny(contextTask, Task.Delay(TimeSpan.FromMinutes(2)))
                    .ConfigureAwait(false);

                if (completed != contextTask)
                {
                    listener.Stop();
                    throw new TimeoutException("Timed out waiting for the authorisation callback.");
                }

                var context = await contextTask.ConfigureAwait(false);

                // Send a friendly completion page to the browser — best-effort, never fatal.
                try
                {
                    const string html =
                        "<html><body><h2>Authentication complete. You may close this window.</h2></body></html>";
                    byte[] buffer = Encoding.UTF8.GetBytes(html);
                    context.Response.ContentType = "text/html";
                    context.Response.ContentLength64 = buffer.Length;
                    await context
                        .Response.OutputStream.WriteAsync(buffer, 0, buffer.Length)
                        .ConfigureAwait(false);
                    context.Response.OutputStream.Close();
                }
                catch
                { /* Ignore — the page is cosmetic only. */
                }

                // Extract the authorisation code (or propagate an error) from the redirect query string.
                string error = context.Request.QueryString["error"];
                if (!string.IsNullOrEmpty(error))
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        $"Authorisation error returned by the server: {error}"
                    );
                }

                string returnedState = context.Request.QueryString["state"];
                if (returnedState != expectedState)
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        "The authorisation callback's state did not match the expected value — "
                            + "rejecting for safety. Please retry the sign-in."
                    );
                }

                authorizationCode = context.Request.QueryString["code"];
                if (string.IsNullOrEmpty(authorizationCode))
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        "The authorisation response did not contain a code."
                    );
                }

                listener.Stop();
            }

            return authorizationCode;
        }
    }
}
